export const TIMEZONES: { value: string; label: string }[] = [
	{ value: 'Pacific/Honolulu',      label: 'Hawaii (HST, UTC−10)' },
	{ value: 'America/Los_Angeles',   label: 'Los Angeles / Vancouver (PT, UTC−8/−7)' },
	{ value: 'America/Denver',        label: 'Denver / Salt Lake City (MT, UTC−7/−6)' },
	{ value: 'America/Chicago',       label: 'Chicago / Dallas (CT, UTC−6/−5)' },
	{ value: 'America/New_York',      label: 'New York / Toronto (ET, UTC−5/−4)' },
	{ value: 'America/Sao_Paulo',     label: 'São Paulo / Brasília (BRT, UTC−3)' },
	{ value: 'Atlantic/Azores',       label: 'Azoren (AZOT, UTC−1)' },
	{ value: 'Europe/London',         label: 'London / Dublin (GMT/BST, UTC±0/+1)' },
	{ value: 'Europe/Paris',          label: 'Paris / Madrid (CET, UTC+1/+2)' },
	{ value: 'Europe/Zurich',         label: 'Zürich / Bern / Wien (MEZ, UTC+1/+2)' },
	{ value: 'Europe/Berlin',         label: 'Berlin / Amsterdam (MEZ, UTC+1/+2)' },
	{ value: 'Europe/Vienna',         label: 'Wien (MEZ, UTC+1/+2)' },
	{ value: 'Europe/Athens',         label: 'Athen / Helsinki (EET, UTC+2/+3)' },
	{ value: 'Europe/Moscow',         label: 'Moskau (MSK, UTC+3)' },
	{ value: 'Asia/Dubai',            label: 'Dubai / Abu Dhabi (GST, UTC+4)' },
	{ value: 'Asia/Kolkata',          label: 'Indien / Mumbai (IST, UTC+5:30)' },
	{ value: 'Asia/Dhaka',            label: 'Dhaka / Almaty (BST, UTC+6)' },
	{ value: 'Asia/Bangkok',          label: 'Bangkok / Jakarta (ICT, UTC+7)' },
	{ value: 'Asia/Singapore',        label: 'Singapur / Kuala Lumpur (SGT, UTC+8)' },
	{ value: 'Asia/Shanghai',         label: 'Peking / Shanghai (CST, UTC+8)' },
	{ value: 'Asia/Tokyo',            label: 'Tokio (JST, UTC+9)' },
	{ value: 'Australia/Sydney',      label: 'Sydney / Melbourne (AEST, UTC+10/+11)' },
	{ value: 'Pacific/Auckland',      label: 'Auckland / Wellington (NZST, UTC+12/+13)' },
	{ value: 'Africa/Johannesburg',   label: 'Johannesburg / Kairo (SAST, UTC+2)' },
];
