// Code generated by Slice Machine. DO NOT EDIT.

import Akkordeon from './Akkordeon/index.svelte';
import GoogleMapEinbetten from './GoogleMapEinbetten/index.svelte';
import Formular from './Formular/index.svelte';
import Titelbereich from './Titelbereich/index.svelte';
import Bild from './Bild/index.svelte';
import Kacheln from './Kacheln/index.svelte';
import Zitat from './Zitat/index.svelte';
import Text from './Text/index.svelte';
import TextMitBild from './TextMitBild/index.svelte';

export const components = {
	accordion: Akkordeon,
	code_einbetten: GoogleMapEinbetten,
	form: Formular,
	hero: Titelbereich,
	image: Bild,
	image_cards: Kacheln,
	quote: Zitat,
	text: Text,
	text_with_image: TextMitBild
};
