// Code generated by Slice Machine. DO NOT EDIT.

import Formular from './Formular/index.svelte';
import Titelbereich from './Titelbereich/index.svelte';
import Bild from './Bild/index.svelte';
import ImageCards from './ImageCards/index.svelte';
import Zitat from './Zitat/index.svelte';
import Text from './Text/index.svelte';
import TextMitBild from './TextMitBild/index.svelte';

export const components = {
	form: Formular,
	hero: Titelbereich,
	image: Bild,
	image_cards: ImageCards,
	quote: Zitat,
	text: Text,
	text_with_image: TextMitBild
};
