// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
	/**
	 * Label field in *Navigation → Links*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.links[].label
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	label: prismic.TitleField;

	/**
	 * Link field in *Navigation → Links*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.links[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Sub-Link von field in *Navigation → Links*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.links[].sub_link
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	sub_link: prismic.KeyTextField;

	/**
	 * Ausklappbare Schaltfläche field in *Navigation → Links*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: navigation.links[].dropdown_link
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	dropdown_link: prismic.BooleanField;

	/**
	 * Hauptnavigation field in *Navigation → Links*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: navigation.links[].main_nav
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	main_nav: prismic.BooleanField;

	/**
	 * Fusszeilen sekundäre Navigation field in *Navigation → Links*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: navigation.links[].footer_sec_nav
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	footer_sec_nav: prismic.BooleanField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
	/**
	 * Links field in *Navigation*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.links[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<NavigationDocumentData>,
	'navigation',
	Lang
>;

type PageDocumentDataSlicesSlice =
	| FormSlice
	| HeroSlice
	| QuoteSlice
	| TextSlice
	| ImageSlice
	| ImageCardsSlice
	| TextWithImageSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Parent field in *Page*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.parent
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	parent: prismic.ContentRelationshipField<'page'>;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

/**
 * Content for Einstellungen documents
 */
interface SettingsDocumentData {
	/**
	 * Site Title field in *Einstellungen*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: Title of the site
	 * - **API ID Path**: settings.site_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	site_title: prismic.TitleField;

	/**
	 * Seiten Untertitel field in *Einstellungen*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.site_sub_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	site_sub_title: prismic.TitleField;

	/**
	 * E-Mail field in *Einstellungen*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.e_mail
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	e_mail: prismic.KeyTextField;

	/**
	 * Verantwortlich (Person/Unternehmen) field in *Einstellungen*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.responsible_person_company
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	responsible_person_company: prismic.KeyTextField;
}

/**
 * Einstellungen document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<SettingsDocumentData>,
	'settings',
	Lang
>;

/**
 * Content for Design Vorlage documents
 */
interface ThemeDocumentData {
	/**
	 * Design Vorlage Bezeichnung field in *Design Vorlage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: theme.theme_name
	 * - **Tab**: Generell
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	theme_name: prismic.KeyTextField;

	/**
	 * Banner Top field in *Design Vorlage*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: theme.banner_top
	 * - **Tab**: Generell
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	banner_top: prismic.BooleanField;

	/**
	 * Textfarbe field in *Design Vorlage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: theme.page_color
	 * - **Tab**: Generell
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	page_color: prismic.ColorField;

	/**
	 * Hintergrundfarbe field in *Design Vorlage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: theme.page_bg_color
	 * - **Tab**: Generell
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	page_bg_color: prismic.ColorField;

	/**
	 * Hauptschrift field in *Design Vorlage*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: theme.body_font
	 * - **Tab**: Generell
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	body_font: prismic.SelectField<'Roboto' | 'Open Sans' | 'Jura'>;

	/**
	 * Navigationsschrift field in *Design Vorlage*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: theme.nav_font
	 * - **Tab**: Generell
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	nav_font: prismic.SelectField<'Roboto' | 'Open Sans' | 'Jura'> /**
	 * Hintergrundfarbe field in *Design Vorlage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: theme.header_bg_color
	 * - **Tab**: Kopfzeile
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */;
	header_bg_color: prismic.ColorField;

	/**
	 * Transparenz der Hintergrundfarbe field in *Design Vorlage*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: Eine Zahl zwischen 1 und 99
	 * - **API ID Path**: theme.header_bg_opacity
	 * - **Tab**: Kopfzeile
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	header_bg_opacity: prismic.NumberField;

	/**
	 * Textfarbe field in *Design Vorlage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: theme.header_color
	 * - **Tab**: Kopfzeile
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	header_color: prismic.ColorField;

	/**
	 * Linkfarbe field in *Design Vorlage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: theme.header_link_color
	 * - **Tab**: Kopfzeile
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	header_link_color: prismic.ColorField;

	/**
	 * Linkfarbe, wenn Maus darüber field in *Design Vorlage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: theme.header_link_hover_color
	 * - **Tab**: Kopfzeile
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	header_link_hover_color: prismic.ColorField /**
	 * Hintergrundfarbe field in *Design Vorlage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: theme.footer_bg_color
	 * - **Tab**: Fusszeile
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */;
	footer_bg_color: prismic.ColorField;

	/**
	 * Textfarbe field in *Design Vorlage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: theme.footer_color
	 * - **Tab**: Fusszeile
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	footer_color: prismic.ColorField;

	/**
	 * Linkfarbe field in *Design Vorlage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: theme.footer_link_color
	 * - **Tab**: Fusszeile
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	footer_link_color: prismic.ColorField;
}

/**
 * Design Vorlage document from Prismic
 *
 * - **API ID**: `theme`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ThemeDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<ThemeDocumentData>,
	'theme',
	Lang
>;

export type AllDocumentTypes = NavigationDocument | PageDocument | SettingsDocument | ThemeDocument;

/**
 * Item in *Formular → Standard → Primary → Formular Felder*
 */
export interface FormSliceDefaultPrimaryFormFieldsItem {
	/**
	 * Formularfeld Label field in *Formular → Standard → Primary → Formular Felder*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.default.primary.form_fields[].field_name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	field_name: prismic.KeyTextField;

	/**
	 * Feld Typ field in *Formular → Standard → Primary → Formular Felder*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.default.primary.form_fields[].field_type
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	field_type: prismic.SelectField<'text' | 'email' | 'textarea' | 'select'>;

	/**
	 * Obligatorisch field in *Formular → Standard → Primary → Formular Felder*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: form.default.primary.form_fields[].required
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	required: prismic.BooleanField;

	/**
	 * Fehlermeldung field in *Formular → Standard → Primary → Formular Felder*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.default.primary.form_fields[].invalid_feedback-text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	'invalid_feedback-text': prismic.KeyTextField;
}

/**
 * Primary content in *Formular → Standard → Primary*
 */
export interface FormSliceDefaultPrimary {
	/**
	 * Formular Titel field in *Formular → Standard → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.default.primary.form_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	form_title: prismic.KeyTextField;

	/**
	 * Formular Instruktionen field in *Formular → Standard → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.default.primary.form_instructions
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	form_instructions: prismic.RichTextField;

	/**
	 * Senden-Schaltflächen-Text field in *Formular → Standard → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.default.primary.submitt_button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	submitt_button_text: prismic.KeyTextField;

	/**
	 * Gesendet Titel field in *Formular → Standard → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.default.primary.submitted_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	submitted_title: prismic.KeyTextField;

	/**
	 * Gesendet Text field in *Formular → Standard → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.default.primary.submitted_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	submitted_text: prismic.RichTextField;

	/**
	 * Formular Felder field in *Formular → Standard → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.default.primary.form_fields[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	form_fields: prismic.GroupField<Simplify<FormSliceDefaultPrimaryFormFieldsItem>>;
}

/**
 * Standard variation for Formular Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FormSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Formular*
 */
type FormSliceVariation = FormSliceDefault;

/**
 * Formular Shared Slice
 *
 * - **API ID**: `form`
 * - **Description**: Formular
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSlice = prismic.SharedSlice<'form', FormSliceVariation>;

/**
 * Primary content in *Titelbereich → Standard → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Text field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Textfarbe field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.color
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	color: prismic.ColorField;

	/**
	 * Schaltflächenlink field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.button_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Schaltflächentext field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text: prismic.KeyTextField;

	/**
	 * Hintergrundbild field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.backgroundImage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	backgroundImage: prismic.ImageField<never>;

	/**
	 * Überlagerungsfarbe field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.overlay_color
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	overlay_color: prismic.ColorField;

	/**
	 * Tranparenz der Überlagerungsfarbe field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.overlay_opacity
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	overlay_opacity: prismic.NumberField;

	/**
	 * Titelbild Höhe field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.banner_height
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	banner_height: prismic.SelectField<'100 %' | '50 %' | '33 %'>;
}

/**
 * Standard variation for Titelbereich Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Titelbereich*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Titelbereich Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Primary content in *Bild → Standard → Primary*
 */
export interface ImageSliceDefaultPrimary {
	/**
	 * Bild field in *Bild → Standard → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Standard variation for Bild Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ImageSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *Bild → Banner → Primary*
 */
export interface ImageSliceBannerPrimary {
	/**
	 * Image field in *Bild → Banner → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image.banner.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Banner variation for Bild Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceBanner = prismic.SharedSliceVariation<
	'banner',
	Simplify<ImageSliceBannerPrimary>,
	never
>;

/**
 * Slice variation for *Bild*
 */
type ImageSliceVariation = ImageSliceDefault | ImageSliceBanner;

/**
 * Bild Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<'image', ImageSliceVariation>;

/**
 * Item in *ImageCards → Default → Primary → Cards*
 */
export interface ImageCardsSliceDefaultPrimaryCardsItem {
	/**
	 * Image field in *ImageCards → Default → Primary → Cards*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_cards.default.primary.cards[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Text field in *ImageCards → Default → Primary → Cards*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_cards.default.primary.cards[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Button Link field in *ImageCards → Default → Primary → Cards*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_cards.default.primary.cards[].buttonLink
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	buttonLink: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Button Text field in *ImageCards → Default → Primary → Cards*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_cards.default.primary.cards[].buttonText
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	buttonText: prismic.KeyTextField;
}

/**
 * Primary content in *ImageCards → Default → Primary*
 */
export interface ImageCardsSliceDefaultPrimary {
	/**
	 * Heading field in *ImageCards → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_cards.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Cards field in *ImageCards → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_cards.default.primary.cards[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	cards: prismic.GroupField<Simplify<ImageCardsSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for ImageCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageCardsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ImageCardsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *ImageCards*
 */
type ImageCardsSliceVariation = ImageCardsSliceDefault;

/**
 * ImageCards Shared Slice
 *
 * - **API ID**: `image_cards`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageCardsSlice = prismic.SharedSlice<'image_cards', ImageCardsSliceVariation>;

/**
 * Primary content in *Zitat → Standart → Primary*
 */
export interface QuoteSliceDefaultPrimary {
	/**
	 * Zitat field in *Zitat → Standart → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quote.default.primary.quote
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	quote: prismic.RichTextField;

	/**
	 * Quelle field in *Zitat → Standart → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quote.default.primary.source
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	source: prismic.KeyTextField;
}

/**
 * Standart variation for Zitat Slice
 *
 * - **API ID**: `default`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<QuoteSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Zitat*
 */
type QuoteSliceVariation = QuoteSliceDefault;

/**
 * Zitat Shared Slice
 *
 * - **API ID**: `quote`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSlice = prismic.SharedSlice<'quote', QuoteSliceVariation>;

/**
 * Primary content in *Text → Standard → Primary*
 */
export interface TextSliceDefaultPrimary {
	/**
	 * Text field in *Text → Standard → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
}

/**
 * Standard variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TextSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *Text → Zwei Spalten → Primary*
 */
export interface TextSliceTwoColumnsPrimary {
	/**
	 * Text field in *Text → Zwei Spalten → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text.twoColumns.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
}

/**
 * Zwei Spalten variation for Text Slice
 *
 * - **API ID**: `twoColumns`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceTwoColumns = prismic.SharedSliceVariation<
	'twoColumns',
	Simplify<TextSliceTwoColumnsPrimary>,
	never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault | TextSliceTwoColumns;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<'text', TextSliceVariation>;

/**
 * Primary content in *TextMitBild → Standard → Primary*
 */
export interface TextWithImageSliceDefaultPrimary {
	/**
	 * Text field in *TextMitBild → Standard → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_image.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Bild field in *TextMitBild → Standard → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_image.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Standard variation for TextMitBild Slice
 *
 * - **API ID**: `default`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TextWithImageSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *TextMitBild → Mit Schaltfläche → Primary*
 */
export interface TextWithImageSliceWithButtonPrimary {
	/**
	 * Text field in *TextMitBild → Mit Schaltfläche → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_image.withButton.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Button Link field in *TextMitBild → Mit Schaltfläche → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_image.withButton.primary.buttonLink
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	buttonLink: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Button Text field in *TextMitBild → Mit Schaltfläche → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_image.withButton.primary.buttonText
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	buttonText: prismic.KeyTextField;

	/**
	 * Image field in *TextMitBild → Mit Schaltfläche → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_image.withButton.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Mit Schaltfläche variation for TextMitBild Slice
 *
 * - **API ID**: `withButton`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceWithButton = prismic.SharedSliceVariation<
	'withButton',
	Simplify<TextWithImageSliceWithButtonPrimary>,
	never
>;

/**
 * Slice variation for *TextMitBild*
 */
type TextWithImageSliceVariation = TextWithImageSliceDefault | TextWithImageSliceWithButton;

/**
 * TextMitBild Shared Slice
 *
 * - **API ID**: `text_with_image`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSlice = prismic.SharedSlice<
	'text_with_image',
	TextWithImageSliceVariation
>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			NavigationDocument,
			NavigationDocumentData,
			NavigationDocumentDataLinksItem,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			SettingsDocument,
			SettingsDocumentData,
			ThemeDocument,
			ThemeDocumentData,
			AllDocumentTypes,
			FormSlice,
			FormSliceDefaultPrimaryFormFieldsItem,
			FormSliceDefaultPrimary,
			FormSliceVariation,
			FormSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			ImageSlice,
			ImageSliceDefaultPrimary,
			ImageSliceBannerPrimary,
			ImageSliceVariation,
			ImageSliceDefault,
			ImageSliceBanner,
			ImageCardsSlice,
			ImageCardsSliceDefaultPrimaryCardsItem,
			ImageCardsSliceDefaultPrimary,
			ImageCardsSliceVariation,
			ImageCardsSliceDefault,
			QuoteSlice,
			QuoteSliceDefaultPrimary,
			QuoteSliceVariation,
			QuoteSliceDefault,
			TextSlice,
			TextSliceDefaultPrimary,
			TextSliceTwoColumnsPrimary,
			TextSliceVariation,
			TextSliceDefault,
			TextSliceTwoColumns,
			TextWithImageSlice,
			TextWithImageSliceDefaultPrimary,
			TextWithImageSliceWithButtonPrimary,
			TextWithImageSliceVariation,
			TextWithImageSliceDefault,
			TextWithImageSliceWithButton
		};
	}
}
