// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type EventDocumentDataSlicesSlice = EventSlice;

/**
 * Content for Event documents
 */
interface EventDocumentData {
	/**
	 * Slice Zone field in *Event*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: event.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<EventDocumentDataSlicesSlice>;
}

/**
 * Event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<EventDocumentData>,
	'event',
	Lang
>;

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
	/**
	 * Label field in *Navigation → Links*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.links[].label
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	label: prismic.TitleField;

	/**
	 * Link field in *Navigation → Links*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.links[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Sub-Link von field in *Navigation → Links*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.links[].sub_link
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	sub_link: prismic.KeyTextField;

	/**
	 * Ausklappbare Schaltfläche field in *Navigation → Links*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: navigation.links[].dropdown_link
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	dropdown_link: prismic.BooleanField;

	/**
	 * Hauptnavigation field in *Navigation → Links*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: navigation.links[].main_nav
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	main_nav: prismic.BooleanField;

	/**
	 * Fusszeilen sekundäre Navigation field in *Navigation → Links*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: navigation.links[].footer_sec_nav
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	footer_sec_nav: prismic.BooleanField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
	/**
	 * Links field in *Navigation*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation.links[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<NavigationDocumentData>,
	'navigation',
	Lang
>;

type PageDocumentDataSlicesSlice =
	| GlobaleEventsSlice
	| EventSlice
	| HtmlCodeSlice
	| CodeEinbettenSlice
	| AccordionSlice
	| FormSlice
	| HeroSlice
	| QuoteSlice
	| TextSlice
	| ImageSlice
	| ImageCardsSlice
	| TextWithImageSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Keine Indexierung field in *Page*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: page.no_index
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	no_index: prismic.BooleanField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

/**
 * Content for Einstellungen documents
 */
interface SettingsDocumentData {
	/**
	 * Website Titel field in *Einstellungen*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: Title of the site
	 * - **API ID Path**: settings.site_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	site_title: prismic.TitleField;

	/**
	 * Website Titel Schriftgrösse field in *Einstellungen*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 1 - 20
	 * - **API ID Path**: settings.site_title_font_size
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	site_title_font_size: prismic.NumberField;

	/**
	 * Website Untertitel field in *Einstellungen*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.site_sub_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	site_sub_title: prismic.TitleField;

	/**
	 * Website Untertitel Schriftgrösse field in *Einstellungen*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 1 - 20
	 * - **API ID Path**: settings.site_sub_title_font_size
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	site_sub_title_font_size: prismic.NumberField;

	/**
	 * E-Mail field in *Einstellungen*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.e_mail
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	e_mail: prismic.KeyTextField;

	/**
	 * Verantwortlich (Person/Unternehmen) field in *Einstellungen*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.responsible_person_company
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	responsible_person_company: prismic.KeyTextField;
}

/**
 * Einstellungen document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<SettingsDocumentData>,
	'settings',
	Lang
>;

/**
 * Content for Design Vorlage documents
 */
interface ThemeDocumentData {
	/**
	 * Design Vorlage Bezeichnung field in *Design Vorlage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: theme.theme_name
	 * - **Tab**: Generell
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	theme_name: prismic.KeyTextField;

	/**
	 * Hintergrundfarbe field in *Design Vorlage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: theme.page_bg_color
	 * - **Tab**: Generell
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	page_bg_color: prismic.ColorField;

	/**
	 * Textfarbe field in *Design Vorlage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: theme.page_color
	 * - **Tab**: Generell
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	page_color: prismic.ColorField;

	/**
	 * Linkfarbe field in *Design Vorlage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: theme.page_link_color
	 * - **Tab**: Generell
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	page_link_color: prismic.ColorField;

	/**
	 * Linkfarbe wenn Maus darüber field in *Design Vorlage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: theme.link_hover_color_text
	 * - **Tab**: Generell
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	link_hover_color_text: prismic.ColorField;

	/**
	 * Linkhintergrundfarbe Maus darüber field in *Design Vorlage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: theme.link_hover_color_bg
	 * - **Tab**: Generell
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	link_hover_color_bg: prismic.ColorField;

	/**
	 * Hauptschrift field in *Design Vorlage*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: theme.body_font
	 * - **Tab**: Generell
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	body_font: prismic.SelectField<'Roboto' | 'Open Sans' | 'Jura' | 'Soleil'>;

	/**
	 * Navigationsschrift field in *Design Vorlage*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: theme.nav_font
	 * - **Tab**: Generell
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	nav_font: prismic.SelectField<'Roboto' | 'Open Sans' | 'Jura'>;

	/**
	 * Favicon field in *Design Vorlage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: theme.favicon
	 * - **Tab**: Generell
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	favicon: prismic.ImageField<never> /**
	 * Logo field in *Design Vorlage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: theme.logo
	 * - **Tab**: Kopfzeile
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */;
	logo: prismic.ImageField<never>;

	/**
	 * Logo Grösse field in *Design Vorlage*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 1 - 20
	 * - **API ID Path**: theme.logo_height
	 * - **Tab**: Kopfzeile
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	logo_height: prismic.NumberField;

	/**
	 * Hintergrundfarbe field in *Design Vorlage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: theme.header_bg_color
	 * - **Tab**: Kopfzeile
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	header_bg_color: prismic.ColorField;

	/**
	 * Transparenz der Hintergrundfarbe field in *Design Vorlage*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 0 - 100 %
	 * - **API ID Path**: theme.header_bg_opacity
	 * - **Tab**: Kopfzeile
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	header_bg_opacity: prismic.NumberField;

	/**
	 * Textfarbe field in *Design Vorlage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: theme.header_color
	 * - **Tab**: Kopfzeile
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	header_color: prismic.ColorField;

	/**
	 * Linkfarbe field in *Design Vorlage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: theme.header_link_color
	 * - **Tab**: Kopfzeile
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	header_link_color: prismic.ColorField;

	/**
	 * Link Schriftgrösse field in *Design Vorlage*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 1 - 5
	 * - **API ID Path**: theme.header_font_size
	 * - **Tab**: Kopfzeile
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	header_font_size: prismic.NumberField;

	/**
	 * Linkfarbe, wenn Maus darüber field in *Design Vorlage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: theme.header_link_hover_color
	 * - **Tab**: Kopfzeile
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	header_link_hover_color: prismic.ColorField /**
	 * Hintergrundfarbe field in *Design Vorlage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: theme.footer_bg_color
	 * - **Tab**: Fusszeile
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */;
	footer_bg_color: prismic.ColorField;

	/**
	 * Textfarbe field in *Design Vorlage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: theme.footer_color
	 * - **Tab**: Fusszeile
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	footer_color: prismic.ColorField;

	/**
	 * Linkfarbe field in *Design Vorlage*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: theme.footer_link_color
	 * - **Tab**: Fusszeile
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	footer_link_color: prismic.ColorField;
}

/**
 * Design Vorlage document from Prismic
 *
 * - **API ID**: `theme`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ThemeDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<ThemeDocumentData>,
	'theme',
	Lang
>;

export type AllDocumentTypes =
	| EventDocument
	| NavigationDocument
	| PageDocument
	| SettingsDocument
	| ThemeDocument;

/**
 * Item in *Akkordeon → Standard → Primary → Akkordeon Elemente*
 */
export interface AccordionSliceDefaultPrimaryAccordionItemsItem {
	/**
	 * Titel field in *Akkordeon → Standard → Primary → Akkordeon Elemente*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordion.default.primary.accordion_items[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * Text field in *Akkordeon → Standard → Primary → Akkordeon Elemente*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordion.default.primary.accordion_items[].content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField;
}

/**
 * Primary content in *Akkordeon → Standard → Primary*
 */
export interface AccordionSliceDefaultPrimary {
	/**
	 * Überschrift field in *Akkordeon → Standard → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordion.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.RichTextField;

	/**
	 * Beschreibung field in *Akkordeon → Standard → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordion.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Akkordeon Elemente field in *Akkordeon → Standard → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordion.default.primary.accordion_items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	accordion_items: prismic.GroupField<Simplify<AccordionSliceDefaultPrimaryAccordionItemsItem>>;
}

/**
 * Standard variation for Akkordeon Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<AccordionSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Akkordeon*
 */
type AccordionSliceVariation = AccordionSliceDefault;

/**
 * Akkordeon Shared Slice
 *
 * - **API ID**: `accordion`
 * - **Description**: Akkordeon
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSlice = prismic.SharedSlice<'accordion', AccordionSliceVariation>;

/**
 * Primary content in *GoogleMapEinbetten → Standard → Primary*
 */
export interface CodeEinbettenSliceDefaultPrimary {
	/**
	 * HTML Code field in *GoogleMapEinbetten → Standard → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: code_einbetten.default.primary.html_code
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	html_code: prismic.RichTextField;

	/**
	 * Transparenz field in *GoogleMapEinbetten → Standard → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: Zahl zwischen 0 und 100 %
	 * - **API ID Path**: code_einbetten.default.primary.opacity
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	opacity: prismic.NumberField;
}

/**
 * Standard variation for GoogleMapEinbetten Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CodeEinbettenSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<CodeEinbettenSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *GoogleMapEinbetten*
 */
type CodeEinbettenSliceVariation = CodeEinbettenSliceDefault;

/**
 * GoogleMapEinbetten Shared Slice
 *
 * - **API ID**: `code_einbetten`
 * - **Description**: CodeEinbetten
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CodeEinbettenSlice = prismic.SharedSlice<'code_einbetten', CodeEinbettenSliceVariation>;

/**
 * Item in *Event → Standart → Primary → Weitere Daten*
 */
export interface EventSliceDefaultPrimaryAdditionalDatesItem {
	/**
	 * Datum field in *Event → Standart → Primary → Weitere Daten*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: event.default.primary.additional_dates[].date
	 * - **Documentation**: https://prismic.io/docs/field#date
	 */
	date: prismic.DateField;
}

/**
 * Primary content in *Event → Standart → Primary*
 */
export interface EventSliceDefaultPrimary {
	/**
	 * Titel field in *Event → Standart → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: event.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Untertitel field in *Event → Standart → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: event.default.primary.sub_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	sub_title: prismic.KeyTextField;

	/**
	 * Beschreibung field in *Event → Standart → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: event.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;

	/**
	 * Start Datum und Zeit field in *Event → Standart → Primary*
	 *
	 * - **Field Type**: Timestamp
	 * - **Placeholder**: *None*
	 * - **API ID Path**: event.default.primary.start_date_time
	 * - **Documentation**: https://prismic.io/docs/field#timestamp
	 */
	start_date_time: prismic.TimestampField;

	/**
	 * End Datum Zeit field in *Event → Standart → Primary*
	 *
	 * - **Field Type**: Timestamp
	 * - **Placeholder**: *None*
	 * - **API ID Path**: event.default.primary.end_date_time
	 * - **Documentation**: https://prismic.io/docs/field#timestamp
	 */
	end_date_time: prismic.TimestampField;

	/**
	 * Ort field in *Event → Standart → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: event.default.primary.location_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	location_text: prismic.RichTextField;

	/**
	 * Google Maps URL field in *Event → Standart → Primary*
	 *
	 * - **Field Type**: GeoPoint
	 * - **Placeholder**: *None*
	 * - **API ID Path**: event.default.primary.geopoint
	 * - **Documentation**: https://prismic.io/docs/field#geopoint
	 */
	geopoint: prismic.GeoPointField;

	/**
	 * Weitere Daten field in *Event → Standart → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: event.default.primary.additional_dates[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	additional_dates: prismic.GroupField<Simplify<EventSliceDefaultPrimaryAdditionalDatesItem>>;
}

/**
 * Standart variation for Event Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<EventSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Event*
 */
type EventSliceVariation = EventSliceDefault;

/**
 * Event Shared Slice
 *
 * - **API ID**: `event`
 * - **Description**: Event
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventSlice = prismic.SharedSlice<'event', EventSliceVariation>;

/**
 * Item in *Formular → Standard → Primary → Formular Felder*
 */
export interface FormSliceDefaultPrimaryFormFieldsItem {
	/**
	 * Formularfeld Label field in *Formular → Standard → Primary → Formular Felder*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.default.primary.form_fields[].field_name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	field_name: prismic.KeyTextField;

	/**
	 * Feld Typ field in *Formular → Standard → Primary → Formular Felder*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.default.primary.form_fields[].field_type
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	field_type: prismic.SelectField<
		'Textfeld' | 'E-Mail' | 'Textbereich' | 'Auswahlliste' | 'Ankreuzfeld' | 'Einzelauswahl'
	>;

	/**
	 * Obligatorisch field in *Formular → Standard → Primary → Formular Felder*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: form.default.primary.form_fields[].required
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	required: prismic.BooleanField;

	/**
	 * Fehlermeldung field in *Formular → Standard → Primary → Formular Felder*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.default.primary.form_fields[].invalid_feedback-text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	'invalid_feedback-text': prismic.KeyTextField;

	/**
	 * Optionen bei Auswahlfeldern field in *Formular → Standard → Primary → Formular Felder*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: mit Komma getrennt
	 * - **API ID Path**: form.default.primary.form_fields[].options
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	options: prismic.KeyTextField;
}

/**
 * Primary content in *Formular → Standard → Primary*
 */
export interface FormSliceDefaultPrimary {
	/**
	 * Formular Titel field in *Formular → Standard → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.default.primary.form_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	form_title: prismic.KeyTextField;

	/**
	 * Formular Instruktionen field in *Formular → Standard → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.default.primary.form_instructions
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	form_instructions: prismic.RichTextField;

	/**
	 * Senden-Schaltflächen-Text field in *Formular → Standard → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.default.primary.submitt_button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	submitt_button_text: prismic.KeyTextField;

	/**
	 * Gesendet Titel field in *Formular → Standard → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.default.primary.submitted_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	submitted_title: prismic.KeyTextField;

	/**
	 * Gesendet Text field in *Formular → Standard → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.default.primary.submitted_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	submitted_text: prismic.RichTextField;

	/**
	 * Formular Felder field in *Formular → Standard → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: form.default.primary.form_fields[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	form_fields: prismic.GroupField<Simplify<FormSliceDefaultPrimaryFormFieldsItem>>;
}

/**
 * Standard variation for Formular Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FormSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Formular*
 */
type FormSliceVariation = FormSliceDefault;

/**
 * Formular Shared Slice
 *
 * - **API ID**: `form`
 * - **Description**: Formular
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSlice = prismic.SharedSlice<'form', FormSliceVariation>;

/**
 * Primary content in *GlobaleEvents → Standart → Primary*
 */
export interface GlobaleEventsSliceDefaultPrimary {
	/**
	 * Events field in *GlobaleEvents → Standart → Primary*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: globale_events.default.primary.events
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	events: prismic.ContentRelationshipField<'event'>;
}

/**
 * Standart variation for GlobaleEvents Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GlobaleEventsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<GlobaleEventsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *GlobaleEvents*
 */
type GlobaleEventsSliceVariation = GlobaleEventsSliceDefault;

/**
 * GlobaleEvents Shared Slice
 *
 * - **API ID**: `globale_events`
 * - **Description**: GlobaleEvents
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GlobaleEventsSlice = prismic.SharedSlice<'globale_events', GlobaleEventsSliceVariation>;

/**
 * Primary content in *Titelbereich → Standard → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Überlappend mit Kopfzeile field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero.default.primary.banner_overlap
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	banner_overlap: prismic.BooleanField;

	/**
	 * Text field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Textfarbe field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.color
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	color: prismic.ColorField;

	/**
	 * Schaltflächenlink field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.button_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Schaltflächentext field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text: prismic.KeyTextField;

	/**
	 * Schaltfläche Hintergrundfarbe field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: hero.default.primary.button_bg_color
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	button_bg_color: prismic.ColorField;

	/**
	 * Schaltfläche Hintergrund Mouseover field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: hero.default.primary.button_bg_color_hover
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	button_bg_color_hover: prismic.ColorField;

	/**
	 * Schaltfläche Text- und Rahmenfarbe field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: hero.default.primary.button_text_color
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	button_text_color: prismic.ColorField;

	/**
	 * Schaltfläche T & R Mouseover field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: hero.default.primary.button_text_color_hover
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	button_text_color_hover: prismic.ColorField;

	/**
	 * Hintergrundbild field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.backgroundImage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	backgroundImage: prismic.ImageField<'mobile'>;

	/**
	 * Bild Überlagerungsfarbe field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.overlay_color
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	overlay_color: prismic.ColorField;

	/**
	 * Transparenz der Überlagerungsfarbe field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 0 - 100 %
	 * - **API ID Path**: hero.default.primary.overlay_opacity
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	overlay_opacity: prismic.NumberField;

	/**
	 * Titelbild Höhe field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 100 %
	 * - **API ID Path**: hero.default.primary.banner_height
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	banner_height: prismic.SelectField<'100 %' | '50 %' | '33 %', 'filled'>;

	/**
	 * Text Überlagerungsfarbe field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.text_overlay_color
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	text_overlay_color: prismic.ColorField;

	/**
	 * Transparenz Text Überlagerungsfarbe field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 0 - 100 %
	 * - **API ID Path**: hero.default.primary.text_overlay_opacity
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	text_overlay_opacity: prismic.NumberField;

	/**
	 * Text Überlagerungsfeld Grösse field in *Titelbereich → Standard → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.text_overlay_padding
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	text_overlay_padding: prismic.SelectField<'klein' | 'mittel' | 'gross'>;
}

/**
 * Standard variation for Titelbereich Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Titelbereich*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Titelbereich Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Primary content in *HtmlCode → Standard → Primary*
 */
export interface HtmlCodeSliceDefaultPrimary {
	/**
	 * HTML Code field in *HtmlCode → Standard → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: html_code.default.primary.html_code
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	html_code: prismic.RichTextField;
}

/**
 * Standard variation for HtmlCode Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HtmlCodeSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HtmlCodeSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *HtmlCode*
 */
type HtmlCodeSliceVariation = HtmlCodeSliceDefault;

/**
 * HtmlCode Shared Slice
 *
 * - **API ID**: `html_code`
 * - **Description**: HtmlCode
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HtmlCodeSlice = prismic.SharedSlice<'html_code', HtmlCodeSliceVariation>;

/**
 * Item in *Bild → Karussell → Primary → Bilder*
 */
export interface ImageSliceCarouselPrimaryImagesItem {
	/**
	 * Bild field in *Bild → Karussell → Primary → Bilder*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image.carousel.primary.images[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Primary content in *Bild → Standard → Primary*
 */
export interface ImageSliceDefaultPrimary {
	/**
	 * Bild field in *Bild → Standard → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Standard variation for Bild Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ImageSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *Bild → Banner → Primary*
 */
export interface ImageSliceBannerPrimary {
	/**
	 * Bild field in *Bild → Banner → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image.banner.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Banner variation for Bild Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceBanner = prismic.SharedSliceVariation<
	'banner',
	Simplify<ImageSliceBannerPrimary>,
	never
>;

/**
 * Primary content in *Bild → Karussell → Primary*
 */
export interface ImageSliceCarouselPrimary {
	/**
	 * Bilder field in *Bild → Karussell → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image.carousel.primary.images[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	images: prismic.GroupField<Simplify<ImageSliceCarouselPrimaryImagesItem>>;
}

/**
 * Karussell variation for Bild Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceCarousel = prismic.SharedSliceVariation<
	'carousel',
	Simplify<ImageSliceCarouselPrimary>,
	never
>;

/**
 * Slice variation for *Bild*
 */
type ImageSliceVariation = ImageSliceDefault | ImageSliceBanner | ImageSliceCarousel;

/**
 * Bild Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<'image', ImageSliceVariation>;

/**
 * Item in *Kacheln → Standard → Primary → Kacheln*
 */
export interface ImageCardsSliceDefaultPrimaryCardsItem {
	/**
	 * Bild field in *Kacheln → Standard → Primary → Kacheln*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_cards.default.primary.cards[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Text field in *Kacheln → Standard → Primary → Kacheln*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_cards.default.primary.cards[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Schaltflächen-Link field in *Kacheln → Standard → Primary → Kacheln*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_cards.default.primary.cards[].buttonLink
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	buttonLink: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Schaltflächen-Text field in *Kacheln → Standard → Primary → Kacheln*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_cards.default.primary.cards[].buttonText
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	buttonText: prismic.KeyTextField;
}

/**
 * Primary content in *Kacheln → Standard → Primary*
 */
export interface ImageCardsSliceDefaultPrimary {
	/**
	 * Titel field in *Kacheln → Standard → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_cards.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	heading: prismic.TitleField;

	/**
	 * Kacheln field in *Kacheln → Standard → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_cards.default.primary.cards[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	cards: prismic.GroupField<Simplify<ImageCardsSliceDefaultPrimaryCardsItem>>;
}

/**
 * Standard variation for Kacheln Slice
 *
 * - **API ID**: `default`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageCardsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ImageCardsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Kacheln*
 */
type ImageCardsSliceVariation = ImageCardsSliceDefault;

/**
 * Kacheln Shared Slice
 *
 * - **API ID**: `image_cards`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageCardsSlice = prismic.SharedSlice<'image_cards', ImageCardsSliceVariation>;

/**
 * Primary content in *Zitat → Standart → Primary*
 */
export interface QuoteSliceDefaultPrimary {
	/**
	 * Zitat field in *Zitat → Standart → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quote.default.primary.quote
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	quote: prismic.RichTextField;

	/**
	 * Quelle field in *Zitat → Standart → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: quote.default.primary.source
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	source: prismic.KeyTextField;
}

/**
 * Standart variation for Zitat Slice
 *
 * - **API ID**: `default`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<QuoteSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Zitat*
 */
type QuoteSliceVariation = QuoteSliceDefault;

/**
 * Zitat Shared Slice
 *
 * - **API ID**: `quote`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSlice = prismic.SharedSlice<'quote', QuoteSliceVariation>;

/**
 * Primary content in *Text → Standard → Primary*
 */
export interface TextSliceDefaultPrimary {
	/**
	 * Text field in *Text → Standard → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
}

/**
 * Standard variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TextSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *Text → Zwei Spalten → Primary*
 */
export interface TextSliceTwoColumnsPrimary {
	/**
	 * Text field in *Text → Zwei Spalten → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text.twoColumns.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
}

/**
 * Zwei Spalten variation for Text Slice
 *
 * - **API ID**: `twoColumns`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceTwoColumns = prismic.SharedSliceVariation<
	'twoColumns',
	Simplify<TextSliceTwoColumnsPrimary>,
	never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault | TextSliceTwoColumns;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<'text', TextSliceVariation>;

/**
 * Primary content in *TextMitBild → Standard → Primary*
 */
export interface TextWithImageSliceDefaultPrimary {
	/**
	 * Text field in *TextMitBild → Standard → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_image.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Bild field in *TextMitBild → Standard → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_image.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Hintergrundfarbe field in *TextMitBild → Standard → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: text_with_image.default.primary.bg_color
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	bg_color: prismic.ColorField;

	/**
	 * Schriftfarbe field in *TextMitBild → Standard → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: Hex-Farbcode (#RRGGBB)
	 * - **API ID Path**: text_with_image.default.primary.color
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	color: prismic.ColorField;

	/**
	 * Abstand oben / unten gleich field in *TextMitBild → Standard → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: text_with_image.default.primary.y_padding_same
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	y_padding_same: prismic.BooleanField;

	/**
	 * Vertikaler Abstand field in *TextMitBild → Standard → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_image.default.primary.y_padding
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	y_padding: prismic.SelectField<'kein Abstand' | 'wenig' | 'mittel' | 'gross'>;

	/**
	 * Bild als Kreis field in *TextMitBild → Standard → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: text_with_image.default.primary.image_round
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	image_round: prismic.BooleanField;
}

/**
 * Standard variation for TextMitBild Slice
 *
 * - **API ID**: `default`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TextWithImageSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *TextMitBild → Mit Schaltfläche → Primary*
 */
export interface TextWithImageSliceWithButtonPrimary {
	/**
	 * Text field in *TextMitBild → Mit Schaltfläche → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_image.withButton.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Button Link field in *TextMitBild → Mit Schaltfläche → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_image.withButton.primary.buttonLink
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	buttonLink: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Button Text field in *TextMitBild → Mit Schaltfläche → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_image.withButton.primary.buttonText
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	buttonText: prismic.KeyTextField;

	/**
	 * Image field in *TextMitBild → Mit Schaltfläche → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_with_image.withButton.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Mit Schaltfläche variation for TextMitBild Slice
 *
 * - **API ID**: `withButton`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceWithButton = prismic.SharedSliceVariation<
	'withButton',
	Simplify<TextWithImageSliceWithButtonPrimary>,
	never
>;

/**
 * Slice variation for *TextMitBild*
 */
type TextWithImageSliceVariation = TextWithImageSliceDefault | TextWithImageSliceWithButton;

/**
 * TextMitBild Shared Slice
 *
 * - **API ID**: `text_with_image`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSlice = prismic.SharedSlice<
	'text_with_image',
	TextWithImageSliceVariation
>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			EventDocument,
			EventDocumentData,
			EventDocumentDataSlicesSlice,
			NavigationDocument,
			NavigationDocumentData,
			NavigationDocumentDataLinksItem,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			SettingsDocument,
			SettingsDocumentData,
			ThemeDocument,
			ThemeDocumentData,
			AllDocumentTypes,
			AccordionSlice,
			AccordionSliceDefaultPrimaryAccordionItemsItem,
			AccordionSliceDefaultPrimary,
			AccordionSliceVariation,
			AccordionSliceDefault,
			CodeEinbettenSlice,
			CodeEinbettenSliceDefaultPrimary,
			CodeEinbettenSliceVariation,
			CodeEinbettenSliceDefault,
			EventSlice,
			EventSliceDefaultPrimaryAdditionalDatesItem,
			EventSliceDefaultPrimary,
			EventSliceVariation,
			EventSliceDefault,
			FormSlice,
			FormSliceDefaultPrimaryFormFieldsItem,
			FormSliceDefaultPrimary,
			FormSliceVariation,
			FormSliceDefault,
			GlobaleEventsSlice,
			GlobaleEventsSliceDefaultPrimary,
			GlobaleEventsSliceVariation,
			GlobaleEventsSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			HtmlCodeSlice,
			HtmlCodeSliceDefaultPrimary,
			HtmlCodeSliceVariation,
			HtmlCodeSliceDefault,
			ImageSlice,
			ImageSliceDefaultPrimary,
			ImageSliceBannerPrimary,
			ImageSliceCarouselPrimaryImagesItem,
			ImageSliceCarouselPrimary,
			ImageSliceVariation,
			ImageSliceDefault,
			ImageSliceBanner,
			ImageSliceCarousel,
			ImageCardsSlice,
			ImageCardsSliceDefaultPrimaryCardsItem,
			ImageCardsSliceDefaultPrimary,
			ImageCardsSliceVariation,
			ImageCardsSliceDefault,
			QuoteSlice,
			QuoteSliceDefaultPrimary,
			QuoteSliceVariation,
			QuoteSliceDefault,
			TextSlice,
			TextSliceDefaultPrimary,
			TextSliceTwoColumnsPrimary,
			TextSliceVariation,
			TextSliceDefault,
			TextSliceTwoColumns,
			TextWithImageSlice,
			TextWithImageSliceDefaultPrimary,
			TextWithImageSliceWithButtonPrimary,
			TextWithImageSliceVariation,
			TextWithImageSliceDefault,
			TextWithImageSliceWithButton
		};
	}
}
