// AUTO-GENERATED by build-customtypes.js — nicht committen
// Änderungen in gating.json vornehmen, dann npm run dev
export const ICON_SLUG_BY_LABEL: Record<string, string> = {
	"Externer Link": "external-link",
	"Menü": "menu",
	"Schließen": "close",
	"Pfeil Rechts Oben": "pfeil-rechts-oben"
};
